src/main/webapp/WEB-INF/appengine-web.xml

- Adds in an xml file that allows for local runs.

Adds appengine config to allow for local runs

---

.gitignore
pom.xml
src/main/java/com/google/sps/KeyConfig.java
src/main/java/com/google/sps/servlets/movie/MovieDetailsServlet.java
src/main/java/com/google/sps/servlets/movie/MovieSearchServlet.java
src/main/resources/config.properties
src/test/java/com/google/sps/servlets/movie/MovieDetailsServletTest.java
src/test/java/com/google/sps/servlets/movie/MovieSearchServletTest.java

- Add "Movie Details" servlet, users will pass in a movie id and get metadata related to the movie
- Adds in template for config.properties
- Update gitignore to match for any .properties files

Movie details

---

mediaphile/dist/app.yaml
src/main/webapp/WEB-INF/appengine-web.xml

- Adds app.yaml for Angular frontend
- Adds service tag to current Java deployment
https://docs.google.com/document/d/1c58bsRW_g3TLpGENdPsHYK6FpcKnHY6n5koalBg6ok8/

Add deployment config for Java and NodeJS

---

src/main/webapp/home.css
src/main/webapp/home.js
src/main/webapp/index.html

Add search bar, and Add title of movies to front end

Dummy frontend

---

src/main/java/com/google/sps/KeyConfig.java
src/main/java/com/google/sps/servlets/book/BookSearchServlet.java
src/main/java/com/google/sps/util/Utils.java
src/test/java/com/google/sps/servlets/book/BookSearchServletTest.java

This servlet parallels the `MovieSearchServlet`. It creates a Books API accessor and creates a query. Since the pagination of the Books API works differently from that of the movies API, we are currently creating pages with 10 results. There is also not an intrinsic results/page maximum from the Google API, so we should probably create our own system of result limiting to unify this.

Add servlet allowing for book searching with the Google Books API

---

pom.xml
src/main/java/com/google/sps/model/queue/EntityDbQueue.java
src/main/java/com/google/sps/model/queue/QueueResponse.java
src/main/java/com/google/sps/model/queue/WantToWatchQueueObject.java
src/main/java/com/google/sps/model/queue/WatchedQueueObject.java
src/main/java/com/google/sps/servlets/queue/EntityListServlet.java
src/test/java/com/google/sps/servlets/DelegatingServletInputStream.java
src/test/java/com/google/sps/servlets/TestDelegatingServletInputStream.java
src/test/java/com/google/sps/servlets/queue/EntityListServletTest.java

- Implements Queue + Previously Watched POST and GET Endpoints
- Implements tests for endpoints
- Adds helper Input Streamer for tests
- Adds google appengine testing dependencies

Implements Queue + Previously Watched POST and GET Endpoints

---

src/main/webapp/home.css
src/main/webapp/home.js
src/main/webapp/index.html

Displays the list of books or movies according to users search. It Display's both Books and Movies in small boxes with a title and description.

Book display

---

mediaphile/src/app/footer/footer.component.html
mediaphile/src/app/footer/footer.component.scss
mediaphile/src/app/footer/footer.component.spec.ts
mediaphile/src/app/footer/footer.component.ts
mediaphile/src/app/header/header.component.html
mediaphile/src/app/header/header.component.scss
mediaphile/src/app/header/header.component.spec.ts
mediaphile/src/app/header/header.component.ts

This is part 2 to the Angular PR, #23 should be merged first.
- Adds Footer and Header to the Angular code
- Footer contains a message about IMDB API.
- The footer and header are contained on every page due to our routing configuration.
- Adds page generation tests.

Part 2 : Angular add Footer and Header

---

mediaphile/src/app/pages/greeting/greeting.component.html
mediaphile/src/app/pages/greeting/greeting.component.scss
mediaphile/src/app/pages/greeting/greeting.component.spec.ts
mediaphile/src/app/pages/greeting/greeting.component.ts

- Adds "greeting" landing page
- This page is a splash page for people who may not be logged in to still use the site
- Contains a search bar, and login / register button
- Adds basic creation test.

Add greeting page with login button

---

mediaphile/src/pages/home/home-entity/home-entity.component.html
mediaphile/src/pages/home/home-entity/home-entity.component.scss
mediaphile/src/pages/home/home-entity/home-entity.component.spec.ts
mediaphile/src/pages/home/home-entity/home-entity.component.ts
mediaphile/src/pages/home/home.component.html
mediaphile/src/pages/home/home.component.scss
mediaphile/src/pages/home/home.component.spec.ts
mediaphile/src/pages/home/home.component.ts
mediaphile/src/pages/home/queue/queue.component.html
mediaphile/src/pages/home/queue/queue.component.scss
mediaphile/src/pages/home/queue/queue.component.spec.ts
mediaphile/src/pages/home/queue/queue.component.ts

- Adds three components, homepage entity, queue entity, and over arching homepage entity 
- Has tab setup for recent activity from friends
- This can be refactored at a later time, just a prototype design for now
- Adds tests for the three components

Add homepage layout

---

mediaphile/src/app/pages/login/login.component.html
mediaphile/src/app/pages/login/login.component.scss
mediaphile/src/app/pages/login/login.component.spec.ts
mediaphile/src/app/pages/login/login.component.ts

- Adds a "Login" page. This login page has a simple button to login, then redirects over to the Google oAuth login system
- Does this by calling login endpoint to get login oAuth endpoint, then redirects to whatever it gets from the API
- In the future this should get a check to make sure we aren't already logged in.
- Adds creation test for /login

Create a "Login Page" for Angular

---

mediaphile/src/app/app.module.ts
mediaphile/src/app/info.service.ts
mediaphile/src/app/pages/book-details/book-details.component.html
mediaphile/src/app/pages/book-details/book-details.component.scss
mediaphile/src/app/pages/book-details/book-details.component.spec.ts
mediaphile/src/app/pages/book-details/book-details.component.ts
mediaphile/src/app/pages/helper/modal/modal.component.html
mediaphile/src/app/pages/helper/modal/modal.component.spec.ts
mediaphile/src/app/pages/helper/modal/modal.component.ts
mediaphile/src/app/pages/home/home-entity/home-entity.component.spec.ts
mediaphile/src/app/pages/home/home-entity/home-entity.component.ts
mediaphile/src/app/pages/home/home.component.html
mediaphile/src/app/pages/login/login.component.spec.ts
mediaphile/src/app/pages/movie-details/movie-details.component.ts
mediaphile/src/app/pages/user-profile/follow-list/follow-entity/follow-entity.component.spec.ts
mediaphile/src/app/pages/user-profile/user-profile.component.spec.ts
src/main/java/com/google/sps/servlets/queue/MediaListItemServlet.java
src/main/resources/config.properties
src/main/webapp/index.html

- Cherry pick out of book-details-display, fixes merge issue

Cherry pick out of book-details-display, fixes merge issue

---

mediaphile/src/app/info.service.ts
mediaphile/src/app/pages/user-profile/follow-list/follow-entity/follow-entity.component.ts
mediaphile/src/app/pages/user-profile/follow-list/follow-list.component.html
mediaphile/src/app/pages/user-profile/user-profile.component.ts

This PR contains some final fixes to the followers frontend.
@kirantumkur This only has minor changes from #39, but it needs to be merged for the demo.
- Rename some variables to reflect the final names of `/follow` parameters
- Now passes down both userId and userObject
- Add a default profile picture
- Fix deletion and posting of reviews

Working followers frontend

---

mediaphile/src/app/pages/search/results/results.component.html
mediaphile/src/app/pages/search/results/results.component.scss
mediaphile/src/app/pages/search/results/results.component.ts
mediaphile/src/app/pages/search/search.component.html
mediaphile/src/app/pages/search/search.component.scss
mediaphile/src/app/pages/search/search.component.ts

- Cleans up the way data is loaded for graceful error handling
- Adds in a no results found error message
- Adds loading indicators
- Adds tab for Xavier's upcoming user search

Fixup and Cleanup for search results page

---

mediaphile/src/app/app.module.ts
mediaphile/src/app/info.service.ts
mediaphile/src/app/pages/search/results/results.component.html
mediaphile/src/app/pages/search/results/results.component.ts
mediaphile/src/app/pages/search/search.component.html
mediaphile/src/app/pages/search/search.component.ts
mediaphile/src/app/pages/user-entity/user-entity.component.html
mediaphile/src/app/pages/user-entity/user-entity.component.scss
mediaphile/src/app/pages/user-entity/user-entity.component.spec.ts
mediaphile/src/app/pages/user-entity/user-entity.component.ts
mediaphile/src/app/pages/user-profile/follow-list/follow-entity/follow-entity.component.ts
src/main/java/com/google/sps/model/follow/FollowListObject.java
src/main/java/com/google/sps/model/user/UserObject.java
src/main/java/com/google/sps/servlets/user/UserServlet.java
src/test/java/com/google/sps/servlets/follow/FollowServletTest.java
src/test/java/com/google/sps/servlets/user/UserServletTest.java

Add user search to UserServlet so a user can search other users. Add a normalized username to the username object for better search handling. Add the list to the Angular Search page.

User search

---

mediaphile/src/app/app.module.ts

- Fixes git merge with missing comma, causes build to fail

Insert comma into app.module.ts

---

mediaphile/src/app/pages/home/activity/activity-entity/activity-entity.component.ts
src/main/java/com/google/sps/servlets/queue/MediaListItemServlet.java
src/test/java/com/google/sps/servlets/queue/MediaListItemServletTest.java

Add username to queue and viewed list object by retreiving the UserObject username, Update test to new changes.

Username to queued and viewed object

---

mediaphile/src/app/pages/book-details/book-details.component.html
mediaphile/src/app/pages/book-details/book-details.component.scss
mediaphile/src/app/pages/book-details/book-details.component.ts

- implements a "Find on Amazon" button.
- Searches amazon for ISBN of book. If the book has no associated ISBN, it won't display the button 
- Doesn't display metadata fields that don't exist.

Implements "Find on Amazon" button

---

mediaphile/src/app/pages/helper/recommendations/recommendations.component.scss
mediaphile/src/app/pages/search/entity/entity.component.scss

- Fixes CSS issue with entities not displaying correctly in grid

CSS Fixups to prevent grid breaks in searches

---

mediaphile/src/app/app.module.ts
mediaphile/src/app/info.service.ts
mediaphile/src/app/pages/helper/review-submit/review-submit.component.html
mediaphile/src/app/pages/helper/review/review-entity/review-entity.component.scss
mediaphile/src/app/pages/helper/review/review.component.html
mediaphile/src/app/pages/helper/review/review.component.scss
mediaphile/src/app/pages/helper/review/review.component.ts
src/main/java/com/google/sps/servlets/review/ReviewServlet.java
src/test/java/com/google/sps/servlets/review/ReviewServletTest.java

- Adds pagination "pageNumber" field to servlet, throws 400 if missing. Counting starts at "1"
- Fixes bug where reviews weren't showing in order by timestamp
- Bumps Title from 25 -> 50
- Fixes break issues with long pieces of text
- Implements pagination from backend system, works the exact same as other pagination by starting at page 1, increments one up for every load. 
- also fixes unit tests

Implements Review Pagination
